# Generated by Django 4.2 on 2023-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender_alter_user_host_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='host_photo',
            field=models.URLField(),
        ),
    ]
