# Generated by Django 4.2 on 2023-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_host_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='host_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
