# Generated by Django 4.2 on 2023-04-08 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(default='United Kingdom', max_length=50)),
                ('city', models.CharField(default='Leeds', max_length=80)),
                ('address', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('pets_allowed', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('football', 'Football'), ('running', 'Running'), ('yoga', 'Yoga')], max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preparation', models.ManyToManyField(to='workout.preparation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
