# Generated by Django 4.2 on 2023-04-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
