# Generated by Django 4.2 on 2023-04-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_name_alter_preparation_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparation',
            options={'verbose_name_plural': 'Preparations'},
        ),
    ]
