# Generated by Django 4.2 on 2023-04-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('workout', '0003_alter_preparation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
