# Generated by Django 4.2 on 2023-04-12 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0004_workout_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to=settings.AUTH_USER_MODEL),
        ),
    ]
