# Generated by Django 4.2 on 2023-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_workout_category_alter_workout_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='host_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
