# Generated by Django 4.2 on 2023-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('workout', 'Workout'), ('experience', 'Experience')], max_length=20),
        ),
    ]
