# Generated by Django 4.2 on 2023-04-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('workout', 'Workout'), ('experience', 'Experience')], max_length=15),
        ),
    ]
