# Generated by Django 4.2 on 2023-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_experience_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
